-- =============================================================================
-- Migración 20260516_categorias_vuelo
-- =============================================================================
-- Refactor de asientos mixtos.
--
-- Antes: cada VUELO tenía UN único tipo_asiento (TURISTA/BUSINESS) con su
-- propio precio_base y conteo de asientos. Para ofrecer dos clases en un
-- mismo vuelo había que crear dos filas distintas, lo cual es feo y
-- difícil de mantener.
--
-- Después: VUELO sigue siendo la "ruta+horario+avión" y se asocia a una
-- nueva tabla CATEGORIAS_VUELO (1..N) donde vive cada combinación de
-- tipo_asiento + precio + asientos.
--
-- Esta migración es ADITIVA: VUELOS no pierde columnas todavía. Para
-- mantener compatibilidad con el código existente (incluido el flujo de
-- reservaciones que aún decrementa VUELOS.asientos_disponibles), un par
-- de triggers mantienen ambos lados sincronizados mientras se completa
-- la migración del write-side en una próxima fase.
-- =============================================================================

-- 1) Tabla nueva CATEGORIAS_VUELO
CREATE TABLE USUARIO_AEROLINEA.CATEGORIAS_VUELO (
  ID_CATEGORIA          NUMBER GENERATED BY DEFAULT AS IDENTITY
                          (MINVALUE 1 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE)
                          NOT NULL,
  ID_VUELO              NUMBER             NOT NULL,
  TIPO_ASIENTO          VARCHAR2(20 BYTE)  NOT NULL,
  PRECIO                NUMBER(10,2)       NOT NULL,
  ASIENTOS_TOTALES      NUMBER             NOT NULL,
  ASIENTOS_DISPONIBLES  NUMBER             NOT NULL,
  FECHA_CREACION        TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_CATEGORIAS_VUELO       PRIMARY KEY (ID_CATEGORIA),
  CONSTRAINT UK_CATEGORIAS_VUELO_TIPO  UNIQUE (ID_VUELO, TIPO_ASIENTO),
  CONSTRAINT CK_CATEGORIAS_TIPO        CHECK (TIPO_ASIENTO IN ('TURISTA','BUSINESS','PRIMERA','PREMIUM_ECONOMY')),
  CONSTRAINT CK_CATEGORIAS_PRECIO      CHECK (PRECIO > 0),
  CONSTRAINT CK_CATEGORIAS_DISP        CHECK (ASIENTOS_DISPONIBLES >= 0 AND ASIENTOS_DISPONIBLES <= ASIENTOS_TOTALES),
  CONSTRAINT FK_CATEGORIAS_VUELO       FOREIGN KEY (ID_VUELO)
    REFERENCES USUARIO_AEROLINEA.VUELOS(ID_VUELO) ON DELETE CASCADE
);

CREATE INDEX IDX_CATEGORIAS_VUELO ON USUARIO_AEROLINEA.CATEGORIAS_VUELO(ID_VUELO);

-- 2) Poblar desde los VUELOS existentes: 1 categoria por vuelo replicando sus datos.
INSERT INTO USUARIO_AEROLINEA.CATEGORIAS_VUELO
  (ID_VUELO, TIPO_ASIENTO, PRECIO, ASIENTOS_TOTALES, ASIENTOS_DISPONIBLES)
SELECT ID_VUELO,
       NVL(TIPO_ASIENTO, 'TURISTA'),
       PRECIO_BASE,
       ASIENTOS_TOTALES,
       ASIENTOS_DISPONIBLES
FROM USUARIO_AEROLINEA.VUELOS;

COMMIT;

-- 3) Trigger: si una reserva (o admin) decrementa VUELOS.asientos_disponibles
-- y ese vuelo tiene exactamente una categoría, aplicamos el mismo delta a la
-- fila correspondiente en CATEGORIAS_VUELO. Si tiene varias categorías ya
-- no podemos saber cuál se reservó solo con VUELOS, así que dejamos que el
-- código nuevo (que sí pasa idCategoria) escriba directamente.
CREATE OR REPLACE TRIGGER USUARIO_AEROLINEA.TR_SYNC_CATEG_FROM_VUELOS
AFTER UPDATE OF ASIENTOS_DISPONIBLES, ASIENTOS_TOTALES, PRECIO_BASE ON USUARIO_AEROLINEA.VUELOS
FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM USUARIO_AEROLINEA.CATEGORIAS_VUELO
   WHERE ID_VUELO = :NEW.ID_VUELO;

  IF v_count = 1 THEN
    UPDATE USUARIO_AEROLINEA.CATEGORIAS_VUELO
       SET ASIENTOS_DISPONIBLES = :NEW.ASIENTOS_DISPONIBLES,
           ASIENTOS_TOTALES     = :NEW.ASIENTOS_TOTALES,
           PRECIO               = :NEW.PRECIO_BASE
     WHERE ID_VUELO             = :NEW.ID_VUELO;
  END IF;
END;
/

-- 4) Trigger inverso: cuando el código nuevo (post-refactor) decrementa
-- una categoría específica, sumamos sobre todas las categorías del vuelo y
-- actualizamos VUELOS.asientos_disponibles. Así el API v1 sigue mostrando
-- un conteo coherente.
CREATE OR REPLACE TRIGGER USUARIO_AEROLINEA.TR_SYNC_VUELOS_FROM_CATEG
AFTER UPDATE OF ASIENTOS_DISPONIBLES, ASIENTOS_TOTALES ON USUARIO_AEROLINEA.CATEGORIAS_VUELO
FOR EACH ROW
DECLARE
  v_total       NUMBER;
  v_disponibles NUMBER;
BEGIN
  SELECT SUM(ASIENTOS_TOTALES), SUM(ASIENTOS_DISPONIBLES)
    INTO v_total, v_disponibles
    FROM USUARIO_AEROLINEA.CATEGORIAS_VUELO
   WHERE ID_VUELO = :NEW.ID_VUELO;

  UPDATE USUARIO_AEROLINEA.VUELOS
     SET ASIENTOS_TOTALES     = v_total,
         ASIENTOS_DISPONIBLES = v_disponibles
   WHERE ID_VUELO             = :NEW.ID_VUELO;
END;
/

COMMIT;
