-- =============================================================================
-- Migración 20260516_categorias_vuelo
-- =============================================================================
-- Refactor de asientos mixtos.
--
-- Antes: cada VUELO tenía UN único tipo_asiento (TURISTA/BUSINESS) con su
-- propio precio_base y conteo de asientos. Para ofrecer dos clases en un
-- mismo vuelo había que crear dos filas distintas, lo cual es feo y
-- difícil de mantener.
--
-- Después: VUELO sigue siendo la "ruta+horario+avión" y se asocia a una
-- nueva tabla CATEGORIAS_VUELO (1..N) donde vive cada combinación de
-- tipo_asiento + precio + asientos.
--
-- Esta migración es ADITIVA: VUELOS no pierde columnas todavía. Para
-- mantener compatibilidad con el código existente (incluido el flujo de
-- reservaciones que aún decrementa VUELOS.asientos_disponibles), un par
-- de triggers mantienen ambos lados sincronizados mientras se completa
-- la migración del write-side en una próxima fase.
--
-- Diseño de los triggers (importante):
--   Un trigger ingenuo dispararía mutating-table (ORA-04091) porque al
--   hacer UPDATE CATEGORIAS_VUELO la propia tabla está bloqueada en
--   row-level, y un SELECT/UPDATE recursivo sobre ella revienta. Para
--   evitarlo:
--     1) TR_SYNC_VUELOS_FROM_CATEG calcula el delta de la fila con
--        :NEW − :OLD y suma ese delta a VUELOS (no necesita leer
--        CATEGORIAS_VUELO).
--     2) Un paquete PKG_SYNC_GUARD lleva una bandera "in_cascade" para
--        evitar que el UPDATE VUELOS que hace el primer trigger reentre
--        al segundo (que también lee CATEGORIAS_VUELO) y forme un ciclo.
--   La bandera se resetea siempre en un EXCEPTION handler para que un
--   error transitorio no deje la conexión con el guard pegado en TRUE.
-- =============================================================================

-- 1) Tabla nueva CATEGORIAS_VUELO
CREATE TABLE USUARIO_AEROLINEA.CATEGORIAS_VUELO (
  ID_CATEGORIA          NUMBER GENERATED BY DEFAULT AS IDENTITY
                          (MINVALUE 1 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE)
                          NOT NULL,
  ID_VUELO              NUMBER             NOT NULL,
  TIPO_ASIENTO          VARCHAR2(20 BYTE)  NOT NULL,
  PRECIO                NUMBER(10,2)       NOT NULL,
  ASIENTOS_TOTALES      NUMBER             NOT NULL,
  ASIENTOS_DISPONIBLES  NUMBER             NOT NULL,
  FECHA_CREACION        TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_CATEGORIAS_VUELO       PRIMARY KEY (ID_CATEGORIA),
  CONSTRAINT UK_CATEGORIAS_VUELO_TIPO  UNIQUE (ID_VUELO, TIPO_ASIENTO),
  CONSTRAINT CK_CATEGORIAS_TIPO        CHECK (TIPO_ASIENTO IN ('TURISTA','BUSINESS','PRIMERA','PREMIUM_ECONOMY')),
  CONSTRAINT CK_CATEGORIAS_PRECIO      CHECK (PRECIO > 0),
  CONSTRAINT CK_CATEGORIAS_DISP        CHECK (ASIENTOS_DISPONIBLES >= 0 AND ASIENTOS_DISPONIBLES <= ASIENTOS_TOTALES),
  CONSTRAINT FK_CATEGORIAS_VUELO       FOREIGN KEY (ID_VUELO)
    REFERENCES USUARIO_AEROLINEA.VUELOS(ID_VUELO) ON DELETE CASCADE
);

CREATE INDEX USUARIO_AEROLINEA.IDX_CATEGORIAS_VUELO
  ON USUARIO_AEROLINEA.CATEGORIAS_VUELO(ID_VUELO);

-- 2) Poblar desde los VUELOS existentes: 1 categoria por vuelo replicando sus datos.
INSERT INTO USUARIO_AEROLINEA.CATEGORIAS_VUELO
  (ID_VUELO, TIPO_ASIENTO, PRECIO, ASIENTOS_TOTALES, ASIENTOS_DISPONIBLES)
SELECT ID_VUELO,
       NVL(TIPO_ASIENTO, 'TURISTA'),
       PRECIO_BASE,
       ASIENTOS_TOTALES,
       ASIENTOS_DISPONIBLES
FROM USUARIO_AEROLINEA.VUELOS;

COMMIT;

-- 3) Package con bandera que rompe la cascada entre los dos triggers.
CREATE OR REPLACE PACKAGE USUARIO_AEROLINEA.PKG_SYNC_GUARD AS
  in_cascade BOOLEAN := FALSE;
END PKG_SYNC_GUARD;
/

-- 4) Trigger CATEGORIAS_VUELO -> VUELOS.
-- Usa :NEW − :OLD para evitar leer la tabla mutante. Marca in_cascade=TRUE
-- antes del UPDATE VUELOS para que el otro trigger no reentre.
CREATE OR REPLACE TRIGGER USUARIO_AEROLINEA.TR_SYNC_VUELOS_FROM_CATEG
AFTER UPDATE OF ASIENTOS_DISPONIBLES, ASIENTOS_TOTALES ON USUARIO_AEROLINEA.CATEGORIAS_VUELO
FOR EACH ROW
DECLARE
  delta_disp NUMBER;
  delta_tot  NUMBER;
BEGIN
  IF USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade THEN RETURN; END IF;
  delta_disp := :NEW.ASIENTOS_DISPONIBLES - :OLD.ASIENTOS_DISPONIBLES;
  delta_tot  := :NEW.ASIENTOS_TOTALES     - :OLD.ASIENTOS_TOTALES;
  IF delta_disp = 0 AND delta_tot = 0 THEN RETURN; END IF;

  USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade := TRUE;
  BEGIN
    UPDATE USUARIO_AEROLINEA.VUELOS
       SET ASIENTOS_DISPONIBLES = ASIENTOS_DISPONIBLES + delta_disp,
           ASIENTOS_TOTALES     = ASIENTOS_TOTALES     + delta_tot
     WHERE ID_VUELO = :NEW.ID_VUELO;
    USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade := FALSE;
  EXCEPTION
    WHEN OTHERS THEN
      USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade := FALSE;
      RAISE;
  END;
END;
/

-- 5) Trigger VUELOS -> CATEGORIAS_VUELO.
-- Solo aplica si el vuelo tiene exactamente 1 categoría (caso v1: cuando
-- el código viejo decrementa VUELOS sin saber de CATEGORIAS_VUELO, hay
-- una sola categoría a la que sincronizar). Si hay varias categorías, no
-- podemos adivinar cuál se reservó y dejamos que el código nuevo (v2) la
-- toque directamente.
CREATE OR REPLACE TRIGGER USUARIO_AEROLINEA.TR_SYNC_CATEG_FROM_VUELOS
AFTER UPDATE OF ASIENTOS_DISPONIBLES, ASIENTOS_TOTALES, PRECIO_BASE ON USUARIO_AEROLINEA.VUELOS
FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  IF USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade THEN RETURN; END IF;
  SELECT COUNT(*) INTO v_count
    FROM USUARIO_AEROLINEA.CATEGORIAS_VUELO WHERE ID_VUELO = :NEW.ID_VUELO;
  IF v_count <> 1 THEN RETURN; END IF;

  USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade := TRUE;
  BEGIN
    UPDATE USUARIO_AEROLINEA.CATEGORIAS_VUELO
       SET ASIENTOS_DISPONIBLES = :NEW.ASIENTOS_DISPONIBLES,
           ASIENTOS_TOTALES     = :NEW.ASIENTOS_TOTALES,
           PRECIO               = :NEW.PRECIO_BASE
     WHERE ID_VUELO             = :NEW.ID_VUELO;
    USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade := FALSE;
  EXCEPTION
    WHEN OTHERS THEN
      USUARIO_AEROLINEA.PKG_SYNC_GUARD.in_cascade := FALSE;
      RAISE;
  END;
END;
/

COMMIT;
