var searchData=
[
  ['v1_2ejs_0',['v1.js',['../dist-node_2v1_8js.html',1,'(Global Namespace)'],['../dist_2v1_8js.html',1,'(Global Namespace)']]],
  ['v1tov6_2ejs_1',['v1ToV6.js',['../dist-node_2v1_to_v6_8js.html',1,'(Global Namespace)'],['../dist_2v1_to_v6_8js.html',1,'(Global Namespace)']]],
  ['v3_2ejs_2',['v3.js',['../dist-node_2v3_8js.html',1,'(Global Namespace)'],['../dist_2v3_8js.html',1,'(Global Namespace)']]],
  ['v35_2ejs_3',['v35.js',['../dist-node_2v35_8js.html',1,'(Global Namespace)'],['../dist_2v35_8js.html',1,'(Global Namespace)']]],
  ['v4_2ejs_4',['v4.js',['../dist-node_2v4_8js.html',1,'(Global Namespace)'],['../dist_2v4_8js.html',1,'(Global Namespace)']]],
  ['v5_2ejs_5',['v5.js',['../dist-node_2v5_8js.html',1,'(Global Namespace)'],['../dist_2v5_8js.html',1,'(Global Namespace)']]],
  ['v6_2ejs_6',['v6.js',['../dist-node_2v6_8js.html',1,'(Global Namespace)'],['../dist_2v6_8js.html',1,'(Global Namespace)']]],
  ['v6tov1_2ejs_7',['v6ToV1.js',['../dist-node_2v6_to_v1_8js.html',1,'(Global Namespace)'],['../dist_2v6_to_v1_8js.html',1,'(Global Namespace)']]],
  ['v7_2ejs_8',['v7.js',['../dist-node_2v7_8js.html',1,'(Global Namespace)'],['../dist_2v7_8js.html',1,'(Global Namespace)']]],
  ['valid_2ejs_9',['valid.js',['../functions_2valid_8js.html',1,'(Global Namespace)'],['../ranges_2valid_8js.html',1,'(Global Namespace)']]],
  ['validate_2dheaders_2ejs_10',['validate-headers.js',['../validate-headers_8js.html',1,'']]],
  ['validate_2doptions_2ejs_11',['validate-options.js',['../validate-options_8js.html',1,'']]],
  ['validate_2ejs_12',['validate.js',['../_0dbabel_2types_2lib_2validators_2validate_8js.html',1,'(Global Namespace)'],['../astro_2dist_2core_2config_2validate_8js.html',1,'(Global Namespace)'],['../astro_2dist_2core_2redirects_2validate_8js.html',1,'(Global Namespace)'],['../uuid_2dist-node_2validate_8js.html',1,'(Global Namespace)'],['../uuid_2dist_2validate_8js.html',1,'(Global Namespace)']]],
  ['validateasymmetrickey_2ejs_13',['validateAsymmetricKey.js',['../validate_asymmetric_key_8js.html',1,'']]],
  ['validatenode_2ejs_14',['validateNode.js',['../validate_node_8js.html',1,'']]],
  ['validation_2ejs_15',['validation.js',['../astro_2dist_2core_2routing_2internal_2validation_8js.html',1,'(Global Namespace)'],['../astro_2dist_2core_2routing_2validation_8js.html',1,'(Global Namespace)'],['../sitemap_2dist_2cjs_2lib_2validation_8js.html',1,'(Global Namespace)'],['../sitemap_2dist_2esm_2lib_2validation_8js.html',1,'(Global Namespace)']]],
  ['validator_2ejs_16',['validator.js',['../validator_8js.html',1,'']]],
  ['validators_2ejs_17',['validators.js',['../validators_8js.html',1,'']]],
  ['value_2ejs_18',['Value.js',['../css-tree_2lib_2syntax_2node_2_value_8js.html',1,'(Global Namespace)'],['../csso_2lib_2replace_2_value_8js.html',1,'(Global Namespace)'],['../csso_2node__modules_2css-tree_2lib_2syntax_2node_2_value_8js.html',1,'(Global Namespace)']]],
  ['value_2ejs_19',['value.js',['../css-tree_2lib_2syntax_2scope_2_value_8js.html',1,'(Global Namespace)'],['../csso_2node__modules_2css-tree_2lib_2syntax_2scope_2_value_8js.html',1,'(Global Namespace)']]],
  ['values_2ejs_20',['values.js',['../micromark-util-symbol_2lib_2values_8js.html',1,'(Global Namespace)'],['../object-inspect_2test_2values_8js.html',1,'(Global Namespace)']]],
  ['valuetonode_2ejs_21',['valueToNode.js',['../value_to_node_8js.html',1,'']]],
  ['var_2ejs_22',['var.js',['../css-tree_2lib_2syntax_2function_2var_8js.html',1,'(Global Namespace)'],['../csso_2node__modules_2css-tree_2lib_2syntax_2function_2var_8js.html',1,'(Global Namespace)']]],
  ['variations_2ejs_23',['variations.js',['../variations_8js.html',1,'']]],
  ['vdmx_2ejs_24',['VDMX.js',['../_v_d_m_x_8js.html',1,'']]],
  ['verify_2dstream_2ejs_25',['verify-stream.js',['../verify-stream_8js.html',1,'']]],
  ['verify_2ejs_26',['verify.js',['../verify_8js.html',1,'']]],
  ['version_2ejs_27',['version.js',['../css-tree_2dist_2version_8js.html',1,'(Global Namespace)'],['../css-tree_2lib_2version_8js.html',1,'(Global Namespace)'],['../csso_2dist_2version_8js.html',1,'(Global Namespace)'],['../csso_2lib_2version_8js.html',1,'(Global Namespace)'],['../csso_2node__modules_2css-tree_2dist_2version_8js.html',1,'(Global Namespace)'],['../csso_2node__modules_2css-tree_2lib_2version_8js.html',1,'(Global Namespace)'],['../nodemon_2lib_2version_8js.html',1,'(Global Namespace)'],['../svgo_2lib_2version_8js.html',1,'(Global Namespace)'],['../uuid_2dist-node_2version_8js.html',1,'(Global Namespace)'],['../uuid_2dist_2version_8js.html',1,'(Global Namespace)']]],
  ['versionedstruct_2ejs_28',['VersionedStruct.js',['../src_2_versioned_struct_8js.html',1,'(Global Namespace)'],['../test_2_versioned_struct_8js.html',1,'(Global Namespace)']]],
  ['versions_2ejs_29',['versions.js',['../versions_8js.html',1,'']]],
  ['vhea_2ejs_30',['vhea.js',['../vhea_8js.html',1,'']]],
  ['vi_2ejs_31',['vi.js',['../vi_8js.html',1,'']]],
  ['videorole_2ejs_32',['VideoRole.js',['../_video_role_8js.html',1,'']]],
  ['view_2dtransitions_2ejs_33',['view-transitions.js',['../view-transitions_8js.html',1,'']]],
  ['view_2ejs_34',['view.js',['../view_8js.html',1,'']]],
  ['virtual_2dfs_2ejs_35',['virtual-fs.js',['../virtual-fs_8js.html',1,'']]],
  ['virtual_2dmodule_2ejs_36',['virtual-module.js',['../virtual-module_8js.html',1,'']]],
  ['visible_2ejs_37',['visible.js',['../visible_8js.html',1,'']]],
  ['visible_2eprebuilt_2ejs_38',['visible.prebuilt.js',['../visible_8prebuilt_8js.html',1,'']]],
  ['visit_2ejs_39',['visit.js',['../visit_8js.html',1,'']]],
  ['vite_2dload_2ejs_40',['vite-load.js',['../vite-load_8js.html',1,'']]],
  ['vite_2dplugin_2dactions_2ejs_41',['vite-plugin-actions.js',['../vite-plugin-actions_8js.html',1,'']]],
  ['vite_2dplugin_2dassets_2ejs_42',['vite-plugin-assets.js',['../vite-plugin-assets_8js.html',1,'']]],
  ['vite_2dplugin_2dastro_2dpreview_2ejs_43',['vite-plugin-astro-preview.js',['../vite-plugin-astro-preview_8js.html',1,'']]],
  ['vite_2dplugin_2dcontainer_2ejs_44',['vite-plugin-container.js',['../vite-plugin-container_8js.html',1,'']]],
  ['vite_2dplugin_2dcontent_2dassets_2ejs_45',['vite-plugin-content-assets.js',['../vite-plugin-content-assets_8js.html',1,'']]],
  ['vite_2dplugin_2dcontent_2dimports_2ejs_46',['vite-plugin-content-imports.js',['../vite-plugin-content-imports_8js.html',1,'']]],
  ['vite_2dplugin_2dcontent_2dvirtual_2dmod_2ejs_47',['vite-plugin-content-virtual-mod.js',['../vite-plugin-content-virtual-mod_8js.html',1,'']]],
  ['vite_2dplugin_2ddev_2dtoolbar_2ejs_48',['vite-plugin-dev-toolbar.js',['../vite-plugin-dev-toolbar_8js.html',1,'']]],
  ['vite_2dplugin_2denv_2ejs_49',['vite-plugin-env.js',['../vite-plugin-env_8js.html',1,'']]],
  ['vite_2dplugin_2dfonts_2ejs_50',['vite-plugin-fonts.js',['../vite-plugin-fonts_8js.html',1,'']]],
  ['vite_2dplugin_2di18n_2ejs_51',['vite-plugin-i18n.js',['../vite-plugin-i18n_8js.html',1,'']]],
  ['vite_2dplugin_2dimport_2dmeta_2denv_2ejs_52',['vite-plugin-import-meta-env.js',['../vite-plugin-import-meta-env_8js.html',1,'']]],
  ['vite_2dplugin_2dmdx_2dpostprocess_2ejs_53',['vite-plugin-mdx-postprocess.js',['../vite-plugin-mdx-postprocess_8js.html',1,'']]],
  ['vite_2dplugin_2dmdx_2ejs_54',['vite-plugin-mdx.js',['../vite-plugin-mdx_8js.html',1,'']]],
  ['vite_2dplugin_2dprefetch_2ejs_55',['vite-plugin-prefetch.js',['../vite-plugin-prefetch_8js.html',1,'']]],
  ['vite_2dplugin_2dserver_2dislands_2ejs_56',['vite-plugin-server-islands.js',['../vite-plugin-server-islands_8js.html',1,'']]],
  ['vite_2dplugin_2dssr_2dassets_2ejs_57',['vite-plugin-ssr-assets.js',['../vite-plugin-ssr-assets_8js.html',1,'']]],
  ['vite_2dplugin_2dtransitions_2ejs_58',['vite-plugin-transitions.js',['../vite-plugin-transitions_8js.html',1,'']]],
  ['vite_2dplugin_2ejs_59',['vite-plugin.js',['../cache_2vite-plugin_8js.html',1,'(Global Namespace)'],['../middleware_2vite-plugin_8js.html',1,'(Global Namespace)'],['../session_2vite-plugin_8js.html',1,'(Global Namespace)']]],
  ['vite_2ejs_60',['vite.js',['../astro_2dist_2core_2errors_2dev_2vite_8js.html',1,'(Global Namespace)'],['../astro_2dist_2core_2logger_2vite_8js.html',1,'(Global Namespace)'],['../astro_2dist_2core_2module-loader_2vite_8js.html',1,'(Global Namespace)'],['../astro_2dist_2vite-plugin-astro-server_2vite_8js.html',1,'(Global Namespace)'],['../vite_2bin_2vite_8js.html',1,'(Global Namespace)']]],
  ['viteutils_2ejs_61',['viteUtils.js',['../vite_utils_8js.html',1,'']]],
  ['vmtx_2ejs_62',['vmtx.js',['../vmtx_8js.html',1,'']]],
  ['vorg_2ejs_63',['VORG.js',['../_v_o_r_g_8js.html',1,'']]]
];
