var annotated_dup =
[
    [ "Napi", "namespace_napi.html", [
      [ "details", "namespace_napi_1_1details.html", [
        [ "CallbackData", "struct_napi_1_1details_1_1_callback_data.html", "struct_napi_1_1details_1_1_callback_data" ],
        [ "CallbackData&lt; Callable, void &gt;", "struct_napi_1_1details_1_1_callback_data_3_01_callable_00_01void_01_4.html", "struct_napi_1_1details_1_1_callback_data_3_01_callable_00_01void_01_4" ],
        [ "FinalizeData", "struct_napi_1_1details_1_1_finalize_data.html", "struct_napi_1_1details_1_1_finalize_data" ],
        [ "AccessorCallbackData", "struct_napi_1_1details_1_1_accessor_callback_data.html", "struct_napi_1_1details_1_1_accessor_callback_data" ],
        [ "HasExtendedFinalizer", "class_napi_1_1details_1_1_has_extended_finalizer.html", null ],
        [ "HasBasicFinalizer", "class_napi_1_1details_1_1_has_basic_finalizer.html", null ],
        [ "vf_number", "struct_napi_1_1details_1_1vf__number.html", null ],
        [ "vf_number&lt; bool &gt;", "struct_napi_1_1details_1_1vf__number_3_01bool_01_4.html", null ],
        [ "vf_utf8_charp", "struct_napi_1_1details_1_1vf__utf8__charp.html", null ],
        [ "vf_utf16_charp", "struct_napi_1_1details_1_1vf__utf16__charp.html", null ],
        [ "vf_utf8_string", "struct_napi_1_1details_1_1vf__utf8__string.html", null ],
        [ "vf_utf16_string", "struct_napi_1_1details_1_1vf__utf16__string.html", null ],
        [ "vf_fallback", "struct_napi_1_1details_1_1vf__fallback.html", null ],
        [ "disjunction", "struct_napi_1_1details_1_1disjunction.html", null ],
        [ "disjunction&lt; B &gt;", "struct_napi_1_1details_1_1disjunction_3_01_b_01_4.html", null ],
        [ "disjunction&lt; B, Bs... &gt;", "struct_napi_1_1details_1_1disjunction_3_01_b_00_01_bs_8_8_8_01_4.html", null ],
        [ "can_make_string", "struct_napi_1_1details_1_1can__make__string.html", null ]
      ] ],
      [ "TypedArrayOf", "class_napi_1_1_typed_array_of.html", "class_napi_1_1_typed_array_of" ],
      [ "Maybe", "class_napi_1_1_maybe.html", "class_napi_1_1_maybe" ],
      [ "BasicEnv", "class_napi_1_1_basic_env.html", "class_napi_1_1_basic_env" ],
      [ "Env", "class_napi_1_1_env.html", "class_napi_1_1_env" ],
      [ "Value", "class_napi_1_1_value.html", "class_napi_1_1_value" ],
      [ "Boolean", "class_napi_1_1_boolean.html", "class_napi_1_1_boolean" ],
      [ "Number", "class_napi_1_1_number.html", "class_napi_1_1_number" ],
      [ "Name", "class_napi_1_1_name.html", "class_napi_1_1_name" ],
      [ "String", "class_napi_1_1_string.html", "class_napi_1_1_string" ],
      [ "Symbol", "class_napi_1_1_symbol.html", "class_napi_1_1_symbol" ],
      [ "TypeTaggable", "class_napi_1_1_type_taggable.html", "class_napi_1_1_type_taggable" ],
      [ "Object", "class_napi_1_1_object.html", "class_napi_1_1_object" ],
      [ "External", "class_napi_1_1_external.html", "class_napi_1_1_external" ],
      [ "Array", "class_napi_1_1_array.html", "class_napi_1_1_array" ],
      [ "ArrayBuffer", "class_napi_1_1_array_buffer.html", "class_napi_1_1_array_buffer" ],
      [ "TypedArray", "class_napi_1_1_typed_array.html", "class_napi_1_1_typed_array" ],
      [ "DataView", "class_napi_1_1_data_view.html", "class_napi_1_1_data_view" ],
      [ "Function", "class_napi_1_1_function.html", "class_napi_1_1_function" ],
      [ "Promise", "class_napi_1_1_promise.html", "class_napi_1_1_promise" ],
      [ "Buffer", "class_napi_1_1_buffer.html", "class_napi_1_1_buffer" ],
      [ "Reference", "class_napi_1_1_reference.html", "class_napi_1_1_reference" ],
      [ "ObjectReference", "class_napi_1_1_object_reference.html", "class_napi_1_1_object_reference" ],
      [ "FunctionReference", "class_napi_1_1_function_reference.html", "class_napi_1_1_function_reference" ],
      [ "Error", "class_napi_1_1_error.html", "class_napi_1_1_error" ],
      [ "TypeError", "class_napi_1_1_type_error.html", "class_napi_1_1_type_error" ],
      [ "RangeError", "class_napi_1_1_range_error.html", "class_napi_1_1_range_error" ],
      [ "CallbackInfo", "class_napi_1_1_callback_info.html", "class_napi_1_1_callback_info" ],
      [ "PropertyDescriptor", "class_napi_1_1_property_descriptor.html", "class_napi_1_1_property_descriptor" ],
      [ "ClassPropertyDescriptor", "class_napi_1_1_class_property_descriptor.html", "class_napi_1_1_class_property_descriptor" ],
      [ "MethodCallbackData", "struct_napi_1_1_method_callback_data.html", "struct_napi_1_1_method_callback_data" ],
      [ "AccessorCallbackData", "struct_napi_1_1_accessor_callback_data.html", "struct_napi_1_1_accessor_callback_data" ],
      [ "InstanceWrap", "class_napi_1_1_instance_wrap.html", "class_napi_1_1_instance_wrap" ],
      [ "ObjectWrap", "class_napi_1_1_object_wrap.html", "class_napi_1_1_object_wrap" ],
      [ "HandleScope", "class_napi_1_1_handle_scope.html", "class_napi_1_1_handle_scope" ],
      [ "EscapableHandleScope", "class_napi_1_1_escapable_handle_scope.html", "class_napi_1_1_escapable_handle_scope" ],
      [ "AsyncContext", "class_napi_1_1_async_context.html", "class_napi_1_1_async_context" ],
      [ "AsyncWorker", "class_napi_1_1_async_worker.html", "class_napi_1_1_async_worker" ],
      [ "MemoryManagement", "class_napi_1_1_memory_management.html", null ],
      [ "VersionManagement", "class_napi_1_1_version_management.html", null ]
    ] ],
    [ "sharp", "namespacesharp.html", [
      [ "InputDescriptor", "structsharp_1_1_input_descriptor.html", "structsharp_1_1_input_descriptor" ]
    ] ],
    [ "BlowfishContext", "struct_blowfish_context.html", "struct_blowfish_context" ],
    [ "ChannelStats", "struct_channel_stats.html", "struct_channel_stats" ],
    [ "Composite", "struct_composite.html", "struct_composite" ],
    [ "MetadataBaton", "struct_metadata_baton.html", "struct_metadata_baton" ],
    [ "MetadataWorker", "class_metadata_worker.html", "class_metadata_worker" ],
    [ "PipelineBaton", "struct_pipeline_baton.html", "struct_pipeline_baton" ],
    [ "PipelineWorker", "class_pipeline_worker.html", "class_pipeline_worker" ],
    [ "StatsBaton", "struct_stats_baton.html", "struct_stats_baton" ],
    [ "StatsWorker", "class_stats_worker.html", "class_stats_worker" ]
];