var dir_a82fbd9cdb3502ab656140735147e86e =
[
    [ "at-rule.js", "at-rule_8js.html", null ],
    [ "comment.js", "postcss_2lib_2comment_8js.html", null ],
    [ "container.js", "postcss_2lib_2container_8js.html", null ],
    [ "css-syntax-error.js", "css-syntax-error_8js.html", null ],
    [ "declaration.js", "postcss_2lib_2_declaration_8js.html", null ],
    [ "document.js", "postcss_2lib_2document_8js.html", null ],
    [ "fromJSON.js", "from_j_s_o_n_8js.html", null ],
    [ "input.js", "postcss_2lib_2input_8js.html", null ],
    [ "lazy-result.js", "lazy-result_8js.html", null ],
    [ "list.js", "postcss_2lib_2_list_8js.html", null ],
    [ "map-generator.js", "map-generator_8js.html", null ],
    [ "no-work-result.js", "no-work-result_8js.html", null ],
    [ "node.js", "postcss_2lib_2node_8js.html", null ],
    [ "parse.js", "postcss_2lib_2parse_8js.html", null ],
    [ "parser.js", "postcss_2lib_2parser_8js.html", null ],
    [ "postcss.js", "postcss_8js.html", null ],
    [ "previous-map.js", "previous-map_8js.html", null ],
    [ "processor.js", "postcss_2lib_2processor_8js.html", null ],
    [ "result.js", "result_8js.html", null ],
    [ "root.js", "postcss_2lib_2root_8js.html", null ],
    [ "rule.js", "postcss_2lib_2_rule_8js.html", null ],
    [ "stringifier.js", "postcss_2lib_2stringifier_8js.html", null ],
    [ "stringify.js", "postcss_2lib_2stringify_8js.html", null ],
    [ "symbols.js", "symbols_8js.html", null ],
    [ "terminal-highlight.js", "terminal-highlight_8js.html", null ],
    [ "tokenize.js", "postcss_2lib_2tokenize_8js.html", null ],
    [ "warn-once.js", "warn-once_8js.html", null ],
    [ "warning.js", "warning_8js.html", null ]
];